# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_add_consumer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_encrypted',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_encrypted',
            field=models.BooleanField(default=False, editable=False),
        )
    ]
